/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class codes_recursive_JNI */

#ifndef _Included_codes_recursive_JNI
#define _Included_codes_recursive_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codes_recursive_JNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_codes_recursive_JNI_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
