/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_JNI */

#ifndef _Included_JNI_JNI
#define _Included_JNI_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_JNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_JNI_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
