/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_ControllerNative */

#ifndef _Included_controller_ControllerNative
#define _Included_controller_ControllerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_ControllerNative
 * Method:    moveMirror
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_controller_ControllerNative_moveMirror
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     controller_ControllerNative
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_ControllerNative_reset
  (JNIEnv *, jobject);

/*
 * Class:     controller_ControllerNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_ControllerNative_test
  (JNIEnv *, jobject);

/*
 * Class:     controller_ControllerNative
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_ControllerNative_quit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
