/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testing_JNI */

#ifndef _Included_testing_JNI
#define _Included_testing_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testing_JNI
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testing_JNI_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
